    state_dict = {'Johor':1,
                    'Kedah':2,
                    'Kelantan':3,
                    'Melaka':4,
                    'Negeri Sembilan':5,
                    'Pahang':6,
                    'Perak':7,
                    'Perlis':8,
                    'Pulau Pinang':9,
                    'Sabah':10,
                    'Sarawak':11,
                    'Selangor':12,
                    'Terengganu':13,
                    'Wilayah Persekutuan':14}

    region_dict = {'Kota Tinggi':1,
                    'Larkin Lama':2,
                    'Muar':3,
                    'Pasir Gudang':4,
                    'Alor Setar':5,
                    'Bakar Arang, Sg. Petani':6,
                    'Langkawi':7,
                    'SMK Tanjung Chat, Kota Bharu':8,
                    'Tanah Merah':9,
                    'Bandaraya Melaka':10,
                    'Bukit Rambai':11,
                    'Nilai':12,
                    'Port Dickson':13,
                    'Seremban':14,
                    'Balok Baru, Kuantan':15,
                    'Indera Mahkota, Kuantan':16,
                    'Jerantut':17,
                    'Jalan Tasek, Ipoh':18,
                    'Kg. Air Putih, Taiping':19,
                    'S K Jalan Pegoh, Ipoh':20,
                    'Seri Manjung':21,
                    'Tanjung Malim':22,
                    'Kangar':23,
                    'Perai':24,
                    'Seberang Jaya 2, Perai':25,
                    'USM':26,
                    'Keningau':27,
                    'Kota Kinabalu':28,
                    'Sandakan':29,
                    'Tawau':30,
                    'Bintulu':31,
                    'ILP Miri':32,
                    'Kapit':33,
                    'Kuching':34,
                    'Limbang':35,
                    'Miri':36,
                    'Samarahan':37,
                    'Sarikei':38,
                    'Sibu':39,
                    'Sri Aman':40,
                    'Banting':41,
                    'Kuala Selangor':42,
                    'Pelabuhan Kelang':43,
                    'Petaling Jaya':44,
                    'Shah Alam':45,
                    'Kemaman':46,
                    'Kuala Terengganu':47,
                    'Paka':48,
                    'Batu Muda,Kuala Lumpur':49,
                    'Cheras,Kuala Lumpur':50,
                    'Labuan':51,
                    'Putrajaya':52}
